version: "3"

services:
  assignment-database:
    image: "postgres:13-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "assignment-db-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=assignment-db"
volumes:
  assignment-db-data: